### ISSUE TITLE
Reported as malicious or possibly malicious by Avast

### ISSUE THREAD

**Issue by Shadow-Tag** [pisoj/og-nettools#2]
Please forgive if this is not the correct venue for advising , After downloading apk via F-Droid on Galaxy A15 5G 128gb 4gb RAM USA  Avast Mobile Security reports application OG Network Tools as containing malware.

**Comment by pisoj** [comment]
Interesting, needs a deeper investigation. I don't think this is device specific. It's probably because malware is usually of small size. **Does `Avast` provide any more details?**

**Comment by pisoj** [comment]
After some trying, nothing seems to work, Avast keeps saying the app is suspicious. I've submitted a false positive report to them, hopefully they will be able to fix it. I'll keep you up to date on the situation.

**Comment by pisoj** [comment]
They say they **cleared the apps reputation** from their database. It may take up to **24 hours** for changes to take effect, if the issue persists, they suggest **manually** trying to **update the virus database** in Avast anti-virus.

I tried reinstalling the app and Avast didn't report it as possibly malicious, so I **think** this is **solved**. Please **confirm** it's the same for you, if so, please **close the issue**.

**Comment by Shadow-Tag** [comment]
Confirmed , Avast no longer blocks the apk!

Thank you!

**Comment by Shadow-Tag** [comment]
OG Network Scanner huh...
